package com.vb.kanjimap_android.ui.theme

import androidx.compose.ui.graphics.Color

val StudyLightBackground = Color(0xFFF7F4EF)
val StudyLightSurface = Color(0xFFFFFCF8)
val StudyLightSurfaceVariant = Color(0xFFF1ECE6)
val StudyLightPrimary = Color(0xFF0E6B4B)
val StudyLightOnPrimary = Color(0xFFFFFFFF)
val StudyLightPrimaryContainer = Color(0xFFDCEFE6)
val StudyLightOnPrimaryContainer = Color(0xFF0E6B4B)
val StudyLightSecondary = Color(0xFF7FA892)
val StudyLightTertiary = Color(0xFFB8CBBE)
val StudyLightOutline = Color(0xFFD7D2CA)
val StudyLightOnBackground = Color(0xFF1E1E1C)
val StudyLightOnSurface = Color(0xFF1E1E1C)
val StudyLightOnSurfaceVariant = Color(0xFF5E625D)
val StudyLightError = Color(0xFFC44B4B)

val StudyDarkBackground = Color(0xFF121714)
val StudyDarkSurface = Color(0xFF18201C)
val StudyDarkSurfaceVariant = Color(0xFF232C27)
val StudyDarkPrimary = Color(0xFF62C095)
val StudyDarkOnPrimary = Color(0xFF0F241A)
val StudyDarkPrimaryContainer = Color(0xFF1E4C38)
val StudyDarkOnPrimaryContainer = Color(0xFFD7F3E6)
val StudyDarkSecondary = Color(0xFF9BB8A8)
val StudyDarkTertiary = Color(0xFF7E9C8A)
val StudyDarkOutline = Color(0xFF3E4A43)
val StudyDarkOnBackground = Color(0xFFECE9E3)
val StudyDarkOnSurface = Color(0xFFECE9E3)
val StudyDarkOnSurfaceVariant = Color(0xFFB7BBB5)
val StudyDarkError = Color(0xFFE07B7B)
